### PR TITLE
fix: Check for no microseconds in timestamp for pubsub message handler

### LINKED ISSUE #160: Sporadic datetime parse error
The following error occurred once on my pubsub function. It's otherwise run fine hundreds of times without any issue.
```python
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/functions_framework/__init__.py", line 174, in view_func
    function(event)
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/firebase_functions/pubsub_fn.py", line 184, in on_message_published_wrapped
    return _message_handler(func, raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/firebase_functions/pubsub_fn.py", line 108, in _message_handler
    time = _dt.datetime.strptime(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.runtime/python/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.runtime/python/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-11-13T12:30:23Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```

Why would that occur?

### PR DESCRIPTION
**Pull request by koenmtb1**
Fixes #160

### CODE REVIEW

**Comment by exaby73** [comment]
@koenmtb1 could you add tests for this?

**Comment by inlined** [comment]
Additionally, please fix the formatting errors

**Comment by inlined** [comment]
Also, Google servers don't typically send microseconds that I'm aware of. Are you seeing problems in production or in the emulator?

**Comment by dblake10** [comment]
@inlined - Having encountered this error today, I can confirm that I'm seeing problems with this in production.
@koenmtb1 - Following up on the testing and formatting requests above (from 9 to 10 weeks ago). It would be nice to get this merged so that others don't encounter this same issue.

**Comment by exaby73** [comment]
Closing in favor of https://github.com/firebase/firebase-functions-python/pull/204

**Pull request closed without merging**
