### PR TITLE
fix: precision timestamp detection issue

### PR DESCRIPTION
**Pull request by ekalosak**
https://github.com/firebase/firebase-functions-python/issues/136

### CODE REVIEW

**Comment by exaby73** [comment]
Hello @ekalosak. Could we add some tests for this to ensure no regression in the future?

**Comment by ekalosak** [comment]
@exaby73 yes I believe I clicked "allow edits from maintainers" so you should be able to modify freely. But more than that, I think this issue requires coordination with the firebase-tools maintainers. They released a new version which was not backwards compatible with firebase-functions-python, so there's not any testing to be done on the FFP side that will prevent such mistakes in the future. That will have to come from the firebase-tools folks, if they care to make releases backwards compatible with other parts of the FireBase ecosystem.

**Comment by exaby73** [comment]
Could you link the PR which added these non-backwards compatible changes so that I may have a look?

**Review by taeold — APPROVED** [review]

**Comment by ekalosak** [comment]
Any updates? What's blocking merge?

**Review by exaby73 — APPROVED** [review]

**Review by Salakar — APPROVED** [review]

**Review by taeold — APPROVED** [review]

**Pull request merged**
